### ISSUE TITLE
Add HPD interval arg to MCMCsummary

### ISSUE THREAD

**Issue by caseyyoungflesh** [caseyyoungflesh/MCMCvis#10]
Possibly use `hdi` function from `HDInterval` package (or calculate de novo)

In the form of an argument, so that 50% col (median) stays, and 2.5% and 97.5% cols are replaced with 100 - N and 0 + N cols, where N = (100 - X)/2 and X is specified HPD interval

**Comment by CCheCastaldo** [comment]
I added this functionality to MCMCsummary on the dev_quantiles branch.

**Comment by caseyyoungflesh** [comment]
@CCheCastaldo Same as #25 : Could you add something to the vignette?

**Comment by CCheCastaldo** [comment]
Added.

**Comment by caseyyoungflesh** [comment]
<img width="569" alt="Screen Shot 2019-09-22 at 10 21 41 PM" src="https://user-images.githubusercontent.com/11355842/65398821-6701b780-dd87-11e9-983e-b6bdc7a7dba0.png">

**Comment by caseyyoungflesh** [comment]
How do you feel about this behavior. Since 0.025 is the first probs it gives you that when you are most likely to want 95%. Plus the warning message. What do you think about a 'quantiles' arg and a 'probs' arg? Maybe that's worse.

**Comment by caseyyoungflesh** [comment]
@CCheCastaldo

**Comment by CCheCastaldo** [comment]
I don't really like a separate quantiles and probs arg since both the quantile function and hpd interval use probabilities as the domain / input. Also, having two arguments is going to add some extra if / else clutter to that part of MCMCsummary. On the other hand, I don't like that the argument is probs (plural) when in some cases we are asking for a scalar. Perhaps instead of a warning we could make the function error out unless a scalar probability is specified when HPD = TRUE, instead of using the first element in the probs vector? Or, even better, when HPD = TRUE and no probs is specified we make it default to 95%? Is that what you were suggesting? If so, then yes I am in favor of that. Sorry for the meandering post here, Asa is screaming at me to be a monster. Check back in a bit.

**Comment by CCheCastaldo** [comment]
Yeah so how about this: If probs are not specified, when HDP = TRUE we default to 95%. If probs are specified and it is a vector and HPD = TRUE we either a) leave the warning or b) have the function throw an error.

**Comment by caseyyoungflesh** [comment]
The default to 95% seems reasonable. But then probs would need to = NULL in the function call. When NULL and HPD = FALSE, probs = c(0.025, 0.5, 0.975). When NULL and HPD = TRUE, probs = 0.5. Not super clear to the user what the default is though by looking at the top bit of the function. I think I like that, though. That's what you meant, right?

**Comment by caseyyoungflesh** [comment]
Sorry just saw that last comment. Yeah throw a warning and use the first, maybe

**Comment by caseyyoungflesh** [comment]
Or error. I guess I don't have strong feelings about that bit

**Comment by CCheCastaldo** [comment]
Yes that is what I meant. I can make the documentation clearer. Should I perform these changes on master?

**Comment by caseyyoungflesh** [comment]
Yep, go for it. Vignette update too

**Comment by CCheCastaldo** [comment]
OK, I redid it using two arguments, `probs` for quantiles andv`prob` for HPD. You were right from the start - it was cleanest this way. I updated all the tests, documentation, and vignettes. However, for some reason when I rebuild the package the `MCMCsummary.R` man file is not updating to reflect the change to the params. Ever run into this malarkey?

**Comment by CCheCastaldo** [comment]
nevermind, figured it out - I forgot to `devtools::document()`.

**Comment by CCheCastaldo** [comment]
all done with this. If you don't mind, quickly scan over the `MCMCsummary.R` man page and the new vignette sections for typos. Thanks.

**Comment by CCheCastaldo** [comment]
ok changed `prob` to `hpd_prob`, fixed vignette, documentation, rebuilt, checked, and pushed to master.

**Comment by caseyyoungflesh** [comment]
Thanks!
