### ISSUE TITLE
parallel model runs

### ISSUE THREAD

**Issue by ceciliaOLearySBU** [caseyyoungflesh/MCMCvis#2]
FYI - with the way code is written, if you have parallel runs in your jags model file, need to change class() of your data even if run in 'rjags' or 'R2jags'. For parallelized models, class lists both 'rjags.parallel' and 'rjags' and so gives an error message when evaluating class(). run this to fix: 

class(model) <- 'rjags'

**Comment by caseyyoungflesh** [comment]
This issue should have been fixed as of 0.9.1. Which version of `MCMCvis` are you using? You're spot on - I'm not sure why the `jags.parallel` function in `R2jags` was written to create objects with two classes. While besides the point, running with the `rjags` and `parallel` packages creates `mcmc.list` objects. If the problem persists, let me know.
