### ISSUE TITLE
MCMCsummary add quantiles argument to function

### ISSUE THREAD

**Issue by caseyyoungflesh** [caseyyoungflesh/MCMCvis#25]
* default set as `quantiles = c(0.025, 0.5, 0.975)` if `NA`, no quantiles displayed
* accept varying lengths for argument - if length of quantiles arg = 1, display only one quantile column

**Comment by CCheCastaldo** [comment]
I added this functionality to MCMCsummary on the dev_quantiles branch.

**Comment by caseyyoungflesh** [comment]
@CCheCastaldo could you change the vignette to reflect the changes?

**Comment by CCheCastaldo** [comment]
Yep, all done.

**Comment by CCheCastaldo** [comment]
Want me to update the vignette for the MCMCplot overlay feature? Maybe you should merge dev_quantile first since I think that functionality was added on master.

**Comment by caseyyoungflesh** [comment]
@CCheCastaldo you mean the two models on one plot? That should be on there

**Comment by caseyyoungflesh** [comment]
Yep, just checked. It is
