### ISSUE TITLE
R bloggers post

### ISSUE THREAD

**Issue by caseyyoungflesh** [caseyyoungflesh/MCMCvis#28]
Might be nice to write up a post for R bloggers about a couple features of the new version of the package, namely 1) plotting two models on the same plot, 2) mention a few other plotting bells and whistles, and 3) pointing out HPD intervals are returned in MCMCsummary if desired.

Maybe the post could fit two version of the same, very simple model - one partial pooling, one no pooling as a sort of use case. Thoughts @CCheCastaldo ? The Lynch Lab blog is already setup to post to R bloggers automatically as long as it's setup to do so.

**Comment by CCheCastaldo** [comment]
Yes let's do this. I'll update the vignettes tomorrow and then we can do the blog post next week so long as I am not in the field.

**Comment by caseyyoungflesh** [comment]
After the vignette is updated I'll merge the dev branch into the master and run the tests. Might be able to get this submitted to CRAN tomorrow or Tuesday (we should get that post written up shortly after submitting it to CRAN, though takes a few days for the binaries to be built on CRAN so a little leeway).
