### ISSUE TITLE
Functions don't process stanfit objects automatically

### ISSUE THREAD

**Issue by jkarreth** [caseyyoungflesh/MCMCvis#3]
If I pass a `stanfit` object to any of the functions, the object is not processed:

	library(rstan)
	scode <- "
	parameters {
	real y[2]; 
	} 
	model {
	y[1] ~ normal(0, 1);
	y[2] ~ double_exponential(0, 2);
	} 
	"
	rstan_object <- stan(model_code = scode, iter = 10, verbose = FALSE) 
	MCMCsummary(object = rstan_object)
	# Error in object[[1]] : this S4 class is not subsettable

But if I convert the object into an MCMC list (via `rstan::As.mcmc.list()`), it works as intended:

	MCMCsummary(object = As.mcmc.list(rstan_object))
	#       mean   sd  2.5%   50% 97.5% Rhat
	# y[1]  0.13 0.77 -1.01  0.10  1.41 1.18
	# y[2]  1.48 6.46 -8.74 -0.45 12.01 1.09
	# lp__ -2.71 2.25 -6.38 -1.48 -0.27 1.77

Adding the converter to `MCMCsummary` should fix this.

**Comment by caseyyoungflesh** [comment]
Thanks for pointing this out! Bug has been fixed in version 0.10.0 now on github. `stanfit` objects process as they should. A series of automated checks have also been put in place to ensure all data types are successfully processed.
