### ISSUE TITLE
no rownames in MCMCsummary ver. 0.13? 

### ISSUE THREAD

**Issue by dslramsey** [caseyyoungflesh/MCMCvis#32]
In version 0.13, MCMCsummary() seems to have lost the rownames attribute recording the parameter names.  This makes it hard interpret multiparameter summaries.

**Comment by CCheCastaldo** [comment]
@dslramsey, which type of MCMC objects are you seeing the rownames being omitted? If the object is not large could you upload it here so I can troubleshoot this? In our testing before the release we didn't see this happening but there may well be a bug. Thanks.

**Comment by caseyyoungflesh** [comment]
@CCheCastaldo looks like this is happening with stanfit output. Thanks for the heads up @dslramsey

**Comment by caseyyoungflesh** [comment]
`MCMCvis::MCMCsummary(stan_data)` param names being displayed as numbers

**Comment by dslramsey** [comment]
It was a stanfit object, fitted with rstan.  Its a bit too large to upload here

**Comment by CCheCastaldo** [comment]
@dslramsey, I just fixed this oversight. Could you download the dev version of `MCCMvis` (0.13.1) from GitHub and make sure the fix works for your own stanfit object? This would be a helpful test for us. Thanks. 

```
install.packages('devtools')
devtools::install_github('caseyyoungflesh/MCMCvis')
```

**Comment by dslramsey** [comment]
@CCheCastaldo, after installing the dev version (0.13.1), the issue appears to be fixed.  Thanks for the speedy update!

**Comment by CCheCastaldo** [comment]
No problem @dslramsey! Thanks very much for pointing out the issue.
