### ISSUE TITLE
MCMCtrace changes my working directory

### ISSUE THREAD

**Issue by kalebentley** [caseyyoungflesh/MCMCvis#40]
On line 62 of MCMCtrace, the working directory for the PDF output is set using _setwd_.  This is not ideal as it changes my current working directory that is defined by my Rproj.  Instead of using _setwd_, you should use _paste_ to define the working directory.  For example, I write PDFs using the following format:
pdf(paste(wd, "PLOT_NAME.pdf", sep="/")

**Comment by caseyyoungflesh** [comment]
Thanks for reporting! Should be all sorted in the dev version (master branch on github) -- passed initial tests, anyway. Might be a few weeks before this is on CRAN.

**Comment by kalebentley** [comment]
Right on!  Thanks, Casey.
