### ISSUE TITLE
Only overlap graph for prior and posterior

### ISSUE THREAD

**Issue by jcavieresg** [caseyyoungflesh/MCMCvis#41]
Hi!

I would like ask a question
¿Can I report only  the overlap in prior and posterior with MCMCtrace?

Regards!

Thanks!

**Comment by caseyyoungflesh** [comment]
Do you want to output the percent overlap to an object in R? If so the below should do the trick:

```
#prior 
PR <- rnorm(15000, 0, 32) #equivalent to dnorm(0, 0.001) in JAGS

#get PPO
PPO <- MCMCtrace(MCMC_data, 
          params = c('beta\\[1\\]', 'beta\\[2\\]', 'beta\\[3\\]'),
          ISB = FALSE,
          priors = PR,
          plot = FALSE,
          PPO_out = TRUE)
```

There is an example at the very end of the vignette (link [here](https://cran.r-project.org/web/packages/MCMCvis/vignettes/MCMCvis.html)) that illustrates how to plot this next to MCMCplot output, if that's useful. Let me know if this does what you're looking for.

**Comment by caseyyoungflesh** [comment]
If you want just the density plot (with overlap) you can use the `type = 'density'` argument for `MCMCtrace`

**Comment by jcavieresg** [comment]
Hi!

Thanks for your reply!
I saw the package description on CRAN and did the following:

intercept = rnorm(12900, 0, 5)         # 12900 number of iterations
beta1 = rnorm(12900, 0, 5)

MCMCtrace(fit, params = c("intercept", "beta1"), excl = NULL, ISB = TRUE, type = "density",
          priors = intercept, PPO_out = TRUE, Rhat = TRUE, n.eff = TRUE, ind = TRUE, pdf = FALSE, 
          xlab_den = "Parameter estimate", ylab_den = "Density", main_den = c("intercept", "beta1"), 
          lwd_den = 2, lwd_pr = 2, lty_den = 1, lty_pr = 2, col_den = "black", col_pr = "red", col_txt = "blue")

and works!

This is a nice library!
