### ISSUE TITLE
Mathsymbols in main_den

### ISSUE THREAD

**Issue by jcavieresg** [caseyyoungflesh/MCMCvis#42]
Hi!

Is possible put math symbols for the names of parameters in "main_den" of MCMCtrace?
Because if we can save an object 'MCMCtrace' (for example 'plot1') as a ggplot object, we could do that! 

Thanks!

**Comment by caseyyoungflesh** [comment]
Thanks for pointing that out. Dev version on github now has these capabilities (just added). 
```
MCMCtrace(MCMC_data, params = 'alpha', pdf = FALSE, main_den = expression(mu))
```
