### ISSUE TITLE
Check to see if JOSS paper can be updated (add authors, etc.)

### ISSUE THREAD

**Issue by caseyyoungflesh** [caseyyoungflesh/MCMCvis#57]

**Comment by caseyyoungflesh** [comment]
Helpful links discussing this:

https://github.com/openjournals/joss/issues/423

http://ivory.idyll.org/blog/2019-authorship-revisiting.html

**Comment by CCheCastaldo** [comment]
Thanks for exploring this, I think we just need to decide if what has been added since the initial publication warrants a new submission to JOSS. The guidelines discussed [here](https://github.com/openjournals/joss/issues/423#issuecomment-402332608) were pretty clear.
