### ISSUE TITLE
MCMCsummary square brackets

### ISSUE THREAD

**Issue by emmatalis** [caseyyoungflesh/MCMCvis#63]
I'm using v0.15.2 and trying to get the MCMCsummary for a single parameter lz[144,4]. The vignette for v0.15.2 makes it seem like this is the current syntax:
```MCMCsummary(model_data_rinits_output, params = c("lz[144, 4]"), ISB = FALSE, exact = TRUE)```
but this gives me the following error:
`Error in MCMCchains(object, params, excl, ISB, exact = exact, mcmc.list = TRUE) : 
  "lz[144, 4]" not found in MCMC output. Check `ISB` and `exact` arguments to make sure the desired parsing methods are being used.`
Note that calling the MCMCsummary for all of "lz" works fine. 
I've uploaded my JAGS output object model_data_rinits_output to google drive here: https://drive.google.com/file/d/17ng8WIYVQImFI6kebMKhMSPY5kBVlCu0/view?usp=sharing

**Comment by CCheCastaldo** [comment]
@emmatalis, I think perhaps the space between 144, 4 caused your problem. This works:

`MCMCsummary(model_data_rinits_output, params = "lz[144,4]", ISB = FALSE, exact = TRUE)`

Does this change work for you?

**Comment by emmatalis** [comment]
It does, thanks!
