### ISSUE TITLE
Option to include more than two objects in plot

### ISSUE THREAD

**Issue by HAB1990** [caseyyoungflesh/MCMCvis#68]
It would be useful to be able to plot multiple objects (models) at the same time in the MCMCvis plot to show the clustering of effects of particular response variables on multiple models using same predictors.

**Comment by caseyyoungflesh** [comment]
Thanks for this. 

Developer notes: Need to determine how best to make this work with the current argument structure. Would objects be provided as a list to one argument? Currently each model is a separate argument, but this won't scale to > 2 models

**Comment by caseyyoungflesh** [comment]
Closing due to poor options for scaling this beyond two models.
