### ISSUE TITLE
rhat seems to have limited digits

### ISSUE THREAD

**Issue by rebeccaltaylor** [caseyyoungflesh/MCMCvis#70]
Hi. I am using the MCMCvis package for the first time. When I use the MCMCsummary command on an mcmc.list object I created from nimble chains run in parallel, I get rhat values exactly equal to 1, regardless of the number I supply to the digits argument or the round argument. When I use gelman.diag from the coda package on the same mcmc.list object, I can print numbers that are not exactly equal to 1. The chains are extremely well converged--the largest rhat from gelman.diag is 1.001, so I am not worried about convergence in the current runs, but I wonder if this is a known behavior for MCMCsummary in general. Thank you!

**Comment by caseyyoungflesh** [comment]
That is known behavior, thanks for checking. The function rounds the Rhat stat to 2 digits, since that is all that folks seem to care about (given the strictest anyone is about this is Rhat <= 1.01). I'll add a note in the man file about the rounding.

**Comment by caseyyoungflesh** [comment]
Actually already in the section for the `round` argument for the `MCMCsummary` but definitely easy to miss!

**Comment by caseyyoungflesh** [comment]
And to clarify, when Rhat = 1.001 is rounded to 1.00, R just displays that as 1.

**Comment by rebeccaltaylor** [comment]
Oh my gosh--you're right. There it is in the helpfile. Thanks for responding so quickly.

Rebecca

Rebecca Taylor
Research Statistician
Alaska Science Center
U. S. Geological Survey
(907) 786-7004

Pronouns: She/her
Please note I sometimes send and answer email outside normal work hours.
This helps me with my schedule but is not intended to pressure others to do the same.
________________________________
From: Casey Youngflesh ***@***.***>
Sent: Saturday, July 16, 2022 1:24 PM
To: caseyyoungflesh/MCMCvis ***@***.***>
Cc: Taylor, Rebecca L ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [caseyyoungflesh/MCMCvis] rhat seems to have limited digits (Issue #70)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Actually already in the section for the round argument for the MCMCsummary but definitely easy to miss!

**Comment by rebeccaltaylor** [comment]
By the way--very helpful package--I should have mentioned that before!

Rebecca Taylor
Research Statistician
Alaska Science Center
U. S. Geological Survey
(907) 786-7004

Pronouns: She/her
Please note I sometimes send and answer email outside normal work hours.
This helps me with my schedule but is not intended to pressure others to do the same.
________________________________
From: Casey Youngflesh ***@***.***>
Sent: Saturday, July 16, 2022 1:24 PM
To: caseyyoungflesh/MCMCvis ***@***.***>
Cc: Taylor, Rebecca L ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [caseyyoungflesh/MCMCvis] rhat seems to have limited digits (Issue #70)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Actually already in the section for the round argument for the MCMCsummary but definitely easy to miss!
