### ISSUE TITLE
Save MCMCplot() output as png or pdf

### ISSUE THREAD

**Issue by johnnymdoubleu** [caseyyoungflesh/MCMCvis#72]
Hi, I am planning on running one of my MCMC samples from a server and output the figures of MCMCplot() is there a way to tackle this other than using pdf() and dev.off()?

**Comment by caseyyoungflesh** [comment]
You're exactly right in that pdf() (or png()) + dev.off() is the best way to do this. No way within the function to do this with MCMCplot.

**Comment by johnnymdoubleu** [comment]
Using the ggplotify package, we can convert the plot to a ggplot by wrapping it around with as.ggplot() function. Then ggsave() works too!

**Comment by caseyyoungflesh** [comment]
Interesting, didn't know that!
